stages:
  - lint
  - test



#flake8:
#  stage: lint
#  image: python:3.9-alpine
#  before_script:
 #   - pip install -q flake8
#  script:
 #   - flake8

#pytest:
#  stage: test
#  image: docker/compose:latest
 # tags:
 #   - docker
 # services:
#    - docker:dind
#  before_script:
#    - docker-compose -f local.yml build
    # Ensure celerybeat does not crash due to non-existent tables
#    - docker-compose -f local.yml run --rm django python manage.py migrate
 #   - docker-compose -f local.yml up -d
#  script:
 #   - docker-compose -f local.yml run django pytest

pytest:
  stage: test
  image: python:3.9
 # tags:
 #   - python
  variables:
    DATABASE_URL2: 'sqlite:////test_db.sqlite3'

  before_script:

    - pip install -r requirements/local.txt

  script:
    - pytest

