stages:
  - lint
  - test

variables:
  POSTGRES_USER: 'test'
  POSTGRES_PASSWORD: 'test'
  POSTGRES_DB: 'planthub_test'
  POSTGRES_HOST_AUTH_METHOD: md5


#flake8:
#  stage: lint
#  image: python:3.9-alpine
#  before_script:
 #   - pip install -q flake8
#  script:
 #   - flake8

#pytest:
#  stage: test
#  image: docker/compose:latest
 # tags:
 #   - docker
 # services:
#    - docker:dind
#  before_script:
#    - docker-compose -f local.yml build
    # Ensure celerybeat does not crash due to non-existent tables
#    - docker-compose -f local.yml run --rm django python manage.py migrate
 #   - docker-compose -f local.yml up -d
#  script:
 #   - docker-compose -f local.yml run django pytest

pytest:
  stage: test
  image: python:3.9
 # tags:
 #   - python
  services:
    - postgres:13.4
  variables:
    DATABASE_URL: pgsql://$POSTGRES_USER:$POSTGRES_PASSWORD@idiv-db1.inf-bb.uni-jena.de:5433/$POSTGRES_DB

  before_script:
   # - apt-get update && apt-get install -y iputils-ping
  #  - ping idiv-db1.inf-bb.uni-jena.de
    - psql -U test -p 5433 -P test -h idiv-db1.inf-bb.uni-jena.de
    - pip install -r requirements/local.txt

  script:
    - pytest


