# Generated by Django 3.1.13 on 2022-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iknow_datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioprojectname', models.CharField(choices=[('PhenObs', 'Phenobs'), ('Glonaf', 'Glonaf'), ('sPlot', 'sPlot')], default='PhenObs', max_length=255)),
                ('provenanceRecord', models.JSONField(default=dict)),
                ('cpaMappings', models.JSONField(default=dict)),
                ('original_table_header', models.JSONField(default=dict)),
                ('source_dataset', models.ManyToManyField(to='iknow_datasets.Dataset')),
            ],
        ),
    ]
