# Generated by Django 3.1.13 on 2022-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_sgp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgp',
            name='original_filename',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
