# Generated by Django 3.1.13 on 2022-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_sgp', '0002_sgp_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgp',
            name='datasets_copied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sgp',
            name='project_copied',
            field=models.BooleanField(default=False),
        ),
    ]
