# Generated by Django 3.1.13 on 2022-09-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_sgp', '0005_remove_sgp_bioprojectname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgp',
            name='cpaMappings',
        ),
    ]
