# Generated by Django 3.2.16 on 2023-04-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_sgp', '0006_remove_sgp_cpamappings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sgp',
            options={'verbose_name': 'SGP (Subgraph Project)', 'verbose_name_plural': 'SGP (Subgraph Projects)'},
        ),
    ]
