# Generated by Django 3.2.16 on 2023-04-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_sgp', '0007_alter_sgp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgp',
            name='provenanceDoc',
            field=models.JSONField(default=dict),
        ),
    ]
