# Generated by Django 3.2.16 on 2023-05-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_sgp', '0008_sgp_provenancedoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgp',
            name='associated_bioproject',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
