# Generated by Django 3.2.16 on 2023-05-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_sgp', '0009_sgp_associated_bioproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgp',
            name='associated_bioproject',
        ),
    ]
