# Generated by Django 3.1.13 on 2022-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(upload_to='images/project_logos/', verbose_name='Project Logo'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='image',
            field=models.FileField(null=True, upload_to='images/person_images/', verbose_name='File'),
        ),
    ]
