# Generated by Django 3.2.16 on 2023-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220902_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFunFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_pair_name', models.CharField(max_length=200, verbose_name='Name of Image Pair')),
                ('front_image', models.FileField(null=True, upload_to='images/funfacts/', verbose_name='Front Image')),
                ('back_image', models.FileField(null=True, upload_to='images/funfacts/', verbose_name='Back Image')),
                ('title_en', models.CharField(max_length=200, verbose_name='Imagetitle in English')),
                ('title_de', models.CharField(max_length=200, verbose_name='Imagetitle in German')),
                ('position', models.PositiveIntegerField(default=0, help_text='Here you can insert the position of the                                            image on the learn page. The higher the position number,                                            the further left the image will be on the page.', verbose_name='Position on Page')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
