# Generated by Django 3.1.13 on 2022-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPAmapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=4096)),
                ('sLabel', models.CharField(max_length=4096)),
                ('p', models.CharField(max_length=4096)),
                ('pLabel', models.CharField(max_length=4096)),
                ('o', models.CharField(max_length=4096)),
                ('oLabel', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='IKNOWclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=4096, unique=True)),
                ('label', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='IKNOWproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=4096, unique=True)),
                ('label', models.CharField(max_length=4096)),
            ],
        ),
    ]
