# Generated by Django 3.1.13 on 2022-09-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=4096)),
                ('column_name', models.CharField(max_length=4096)),
                ('column_type', models.CharField(max_length=4096)),
                ('column_category', models.CharField(max_length=4096)),
                ('column_subcategory', models.CharField(max_length=4096)),
                ('column_URI', models.CharField(max_length=4096)),
                ('value', models.CharField(max_length=4096)),
                ('ui_element_type', models.CharField(max_length=4096)),
            ],
        ),
    ]
