# Generated by Django 3.1.13 on 2022-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_manager', '0002_querymetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_label', models.CharField(max_length=4096)),
                ('main_category_uri', models.CharField(max_length=4096)),
                ('sub_category_label', models.CharField(max_length=4096)),
                ('sub_category_uri', models.CharField(max_length=4096, unique=True)),
            ],
        ),
    ]
