# Generated by Django 3.1.13 on 2022-09-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_manager', '0004_auto_20220921_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='IknowEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_number', models.CharField(max_length=1024)),
                ('label', models.CharField(max_length=4096)),
            ],
        ),
    ]
