# Generated by Django 3.1.13 on 2022-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_manager', '0006_auto_20220928_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iknowentity',
            name='uri_number',
        ),
        migrations.AddField(
            model_name='iknowentity',
            name='uri',
            field=models.CharField(max_length=10000, null=True, unique=True),
        ),
    ]
