# Generated by Django 3.2.16 on 2023-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_manager', '0007_auto_20220928_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpamapping',
            options={'verbose_name': 'CPA Mapping', 'verbose_name_plural': 'CPA Mappings'},
        ),
        migrations.AlterModelOptions(
            name='headerclass',
            options={'verbose_name': 'Header Class', 'verbose_name_plural': 'Header Classes'},
        ),
        migrations.AlterModelOptions(
            name='iknowclass',
            options={'verbose_name': 'iKNOW Class', 'verbose_name_plural': 'iKNOW Classes'},
        ),
        migrations.AlterModelOptions(
            name='iknowentity',
            options={'verbose_name': 'iKNOW Entity', 'verbose_name_plural': 'iKNOW Entities'},
        ),
        migrations.AlterModelOptions(
            name='iknowproperty',
            options={'verbose_name': 'iKNOW Property', 'verbose_name_plural': 'iKNOW Properties'},
        ),
        migrations.AlterModelOptions(
            name='querymetadata',
            options={'verbose_name': 'Query Metadata', 'verbose_name_plural': 'Query Metadata'},
        ),
        migrations.AlterField(
            model_name='cpamapping',
            name='p',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='cpamapping',
            name='pLabel',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
