# Generated by Django 3.1.13 on 2022-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iknow_sgp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1023, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SGPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionname', models.CharField(default='', max_length=255)),
                ('bioprojectname', models.CharField(default='', max_length=1023)),
                ('description', models.CharField(default='', max_length=2000)),
                ('cpaMappings', models.JSONField(default=dict)),
                ('subclassMappings', models.JSONField(default=dict)),
                ('associated_sgprojects', models.ManyToManyField(to='iknow_sgp.SGP')),
            ],
        ),
    ]
