# Generated by Django 3.1.13 on 2022-09-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iknow_sgpc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgpc',
            name='collection_prov_rec',
            field=models.JSONField(default=dict),
        ),
    ]
